### PR TITLE
Added Translation feature

### PR DESCRIPTION
**Pull request by rensortino**
The feature I added to the existing website is the ability to translate all text in the page, based on the spoken languages, which will be configured in the translations.json file

### CODE REVIEW

**Comment by erikswed** [comment]
nice I was just needing this

**Comment by jcoelho93** [comment]
Thank you for the PR. However I don’t think this is the best approach for translating. Also every new feature should be started as an issue so that we can discuss and agree on the best approach.

I will update the contribution guide to reflect this
 
Thank you anyways 👍

**Comment by rensortino** [comment]
Ok, thank you for the feedback, I will keep this in mind for next times. 

Do you have any suggestion for a better approach to implement translations?

Best regards

**Comment by jcoelho93** [comment]
> Ok, thank you for the feedback, I will keep this in mind for next times.
> 
> Do you have any suggestion for a better approach to implement translations?
> 
> Best regards
@rensortino 
First of all I would use some existing library or service, probably Google Cloud Translation API, which actually works really well in this case (ie https://translate.google.com/translate?sl=en&tl=pt&u=https://jcoelho93.netlify.com).
Keeping a `translations.json` file with repeated content for every language you need is a big no no. maintenance nightmare.
And then the translation should be optional per React component since some components should not be translated. For example the articles.
Having said this, a translation feature is not something I need for my personal webpage so I would not add it at the moment, it might be helpful for others though. ;)

**Comment by rensortino** [comment]
Thank you for pointing out the best practices, I will retry on another PR eventually 👍

**Pull request closed without merging**
